/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AeIconifyComponent {
    /**
    * Title for the panel
    */
    'aetitle': string;
    /**
    * SVG content
    */
    'svgcontent': string;
    /**
    * Show/Hide the panel
    */
    'toggle': () => Promise<void>;
  }
}

declare global {


  interface HTMLAeIconifyComponentElement extends Components.AeIconifyComponent, HTMLStencilElement {}
  var HTMLAeIconifyComponentElement: {
    prototype: HTMLAeIconifyComponentElement;
    new (): HTMLAeIconifyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'ae-iconify-component': HTMLAeIconifyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AeIconifyComponent extends JSXBase.HTMLAttributes<HTMLAeIconifyComponentElement> {
    /**
    * Title for the panel
    */
    'aetitle'?: string;
    /**
    * SVG content
    */
    'svgcontent'?: string;
  }

  interface IntrinsicElements {
    'ae-iconify-component': AeIconifyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


